/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#131313",
        "on-error": "#690005",
        "outline-variant": "#464555",
        "on-tertiary-fixed": "#3d0026",
        "secondary": "#ffb783",
        "on-secondary-fixed": "#301400",
        "primary-fixed": "#e1e0ff",
        "on-secondary-container": "#451f00",
        "secondary-fixed-dim": "#ffb783",
        "tertiary-fixed": "#ffd8e7",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed-dim": "#ffafd3",
        "tertiary": "#ffafd3",
        "outline": "#918fa1",
        "on-tertiary": "#620040",
        "on-secondary": "#4f2500",
        "on-tertiary-container": "#ffcee2",
        "on-surface-variant": "#c7c4d8",
        "on-primary": "#1000a9",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-bright": "#393939",
        "error": "#ffb4ab",
        "secondary-fixed": "#ffdcc5",
        "inverse-on-surface": "#313030",
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1c1b1b",
        "tertiary-container": "#a63274",
        "surface": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "secondary-container": "#d97722",
        "primary": "#c0c1ff",
        "primary-container": "#4b4dd8",
        "on-primary-container": "#d9d8ff",
        "inverse-primary": "#494bd6",
        "surface-variant": "#353534",
        "on-primary-fixed": "#07006c",
        "surface-container-highest": "#353534",
        "on-secondary-fixed-variant": "#713700",
        "on-tertiary-fixed-variant": "#85145a",
        "surface-tint": "#c0c1ff"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
